# docker-compose.yml
services:
  frontend:
    build: ./content
    ports:
      - "80:80"
    #depends_on:
    #  - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    #depends_on:
    #  - mediagen
    #  - container_llm
    networks:
      - mynetwork
    environment:
      - MEDIA_GEN_URL=http://mediagen:9001
      - LLM_URL=http://container_llm:9000

  mediagen:
    build: ./MediaGen
    ports:
      - "5001:9001"
    volumes:
      - ./model_cache:/app/model_cache  
    runtime: nvidia  
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - mynetwork

  container_llm:
    build: ./container_LLM
    ports:
      - "5002:9000"
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 16G  
          cpus: '4'    
        reservations:
          memory: 8G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TRANSFORMERS_CACHE=/model_cache
      - HF_HOME=/model_cache
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
    volumes:
      - ./model_cache:/model_cache  
      - ./offload:/offload         
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge