services:
  frontend:
    build: ./content
    ports:
      - "80:80"
    #depends_on:
    #  - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    #depends_on:
    #  - mediagen
    #  - container_llm
    networks:
      - mynetwork
    environment:
      - MEDIA_GEN_URL=http://mediagen:9001
      - LLM_URL=http://container_llm:9000

  mediagen:
    build: ./MediaGen
    ports:
      - "5001:9001"
    networks:
      - mynetwork

  container_llm:
    build: ./container_LLm
    ports:
      - "5002:9000"
    command: gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:9000 app:app
    runtime: nvidia    
    networks:
      - mynetwork

networks:
  mynetwork:
