services:
  frontend:
    build: ./content
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mediagen
      - container_llm
    networks:
      - mynetwork
    environment:
      - MEDIA_GEN_URL=http://mediagen:5000
      - LLM_URL=http://container_llm:5000

  mediagen:
    build: ./MediaGen
    ports:
      - "5001:5000"
    networks:
      - mynetwork

  container_llm:
    build: ./container_LLM
    ports:
      - "5002:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
