version: '3.8'

services:
  frontend:
    build: ./frontend_flask
    ports:
      - "5000:5000"

  ai-logic:
    build: ./ai_logic
    ports:
      - "8000:8000"

  media-generator:
    build: ./media_generator
    ports:
      - "8001:8001"

  game-db:
    build: ./game_db
    ports:
      - "8002:8002"
